package com.exceptionhandling;

public class ThrowsCase4 {

	// Case - 4a
	
//	public static void main(String[] args) 
//	{
//	   	try
//	   	{
//	   		throw new ArithmeticException("/by zero");
//	   	}
//	   	catch(ArithmeticException e)
//	   	{
//	   		System.out.println("Hi..Hello");
//	   	}	   	
//
//	}
	
	// Case - 4b
	
//	public static void main(String[] args) 
//	{
//	   	try
//	   	{
//	   		throw new NullPointerException();
//	   	}
//	   	catch(NullPointerException e)
//	   	{
//	   		System.out.println("Hi..Hello");
//	   	}	   	
//	}
	
	
	// Case - 4c
	
//	public static void main(String[] args) 
//	{
//	   	try
//	   	{
//	   		throw new Exception();
//	   	}
//	   	catch(Exception e)
//	   	{
//	   		System.out.println("Hi..Hello");
//	   	}	   	
//	}
	
	// Case - 4c
	
//	public static void main(String[] args) 
//	{
//	   	try
//	   	{
//	   		throw new Error();
//	   	}
//	   	catch(Error e)
//	   	{
//	   		System.out.println("Hi..Hello");
//	   	}	   	
//	}
	
	// Case - 4d
	
	public static void main(String[] args) 
	{
	   	try
	   	{
	   		throw new InterruptedException();
	   	}
	   	catch(InterruptedException e)
	   	{
	   		System.out.println("Hi..Hello");
	   	}	   	
	}


}
